### ISSUE TITLE
Illegal string offset

### ISSUE THREAD

**Issue by kuoruan** [Automattic/wp-super-cache#153]
```
2016/11/12 10:40:25 [error] 1457#1457: *1671 FastCGI sent in stderr: "PHP message: PHP Warning:  Illegal string offset 'uri' in /home/wwwroot/blog/wp-content/plugins/wp-super-cache/wp-cache-phase2.php on line 862
PHP message: PHP Warning:  Illegal string offset 'blog_id' in /home/wwwroot/blog/wp-content/plugins/wp-super-cache/wp-cache-phase2.php on line 863
PHP message: PHP Warning:  Illegal string offset 'post' in /home/wwwroot/blog/wp-content/plugins/wp-super-cache/wp-cache-phase2.php on line 864
PHP message: PHP Warning:  Illegal string offset 'key' in /home/wwwroot/blog/wp-content/plugins/wp-super-cache/wp-cache-phase2.php on line 865
PHP message: PHP Warning:  Illegal string offset 'headers' in /home/wwwroot/blog/wp-content/plugins/wp-super-cache/wp-cache-phase2.php on line 871" while reading response header from upstream, client: 59.109.151.130, server: blog.kuoruan.com, request: "GET /110.html HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock:", host: "blog.kuoruan.com"
2016/11/12 10:40:25 [error] 1457#1457: *1671 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Cannot use string offset as an array in /home/wwwroot/blog/wp-content/plugins/wp-super-cache/wp-cache-phase2.php:871
Stack trace:
#0 /home/wwwroot/blog/wp-content/plugins/wp-super-cache/wp-cache-phase2.php(315): wp_cache_shutdown_callback()
#1 [internal function]: wp_cache_ob_callback('<!DOCTYPE HTML>...', 9)
#2 /home/wwwroot/blog/wp-includes/functions.php(3673): ob_end_flush()
#3 /home/wwwroot/blog/wp-includes/class-wp-hook.php(298): wp_ob_end_flush_all('')
#4 /home/wwwroot/blog/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
#5 /home/wwwroot/blog/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#6 /home/wwwroot/blog/wp-includes/load.php(669): do_action('shutdown')
#7 [internal function]: shutdown_action_hook()
#8 {main}
  thrown in /home/wwwroot/blog/wp-content/plugins/wp-super-cache/wp-cache-phase2.php on line 871" while reading upstream, client: 59.109.151.130, server: blog.kuoruan.com, request: "GET /110.html HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock:", host: "******"
```

**Comment by kuoruan** [comment]
https://github.com/Automattic/wp-super-cache/blob/master/wp-cache-phase2.php#L392 should be ```$wp_cache_meta = array();```

**Comment by foxontherock** [comment]
Looks like they fixed the issue, I just got that file and I have no more warnings. But, it's not available for now as an official wordpress plugin update.

https://github.com/Automattic/wp-super-cache/blob/master/wp-cache-phase2.php

**Comment by kraftbj** [comment]
We'll have a new release soon. Waiting on a couple high impact PRs to settle and land first.
